### ISSUE TITLE
Hand in files for completing chapters

### ISSUE THREAD

**Issue by TheJackiMonster** [MarHai/iiigel#12]
The user can hand in some files from his cloud which were used to complete tasks in the current chapter. So the leader of the group can watch these files and its result ( by interpreters ) to decide if the user can step to the next chapter or let him try again.

**Comment by MarHai** [comment]
this is covered by planning (i.e., in the requirement specification).
at the time of handing in the user's "cloud" gets "screenshotted" (serialized) and is put into a temporary column within the hand-in table.

**Comment by TheJackiMonster** [comment]
Ah, ok I understand. So we send just a copy of the current cloud as json or similar in a column of the 'handin'-table.. right?

**Comment by MarHai** [comment]
yes, that was the intention :)
