### ISSUE TITLE
Leaders are watching

### ISSUE THREAD

**Issue by TheJackiMonster** [MarHai/iiigel#13]
The leader of a group can see in some kind of list who is online in his group and what's their current progress about.

**Comment by MarHai** [comment]
I guess this should be visible within the group-admin view.

**Comment by TheJackiMonster** [comment]
But I think it's important that leaders of groups can only edit their own groups in a more intuitive view. So maybe there's still something to do.

**Comment by MarHai** [comment]
Having an intuitive "teacher's live mode" besides the group-admin mode sounds good to me. We should, then, collect ideas on what is visible there, what needs to be possible there, and what is not necessary on this page (as there is the group-admin page as well).

necessary
- overview of participants, incl. each participant's ...
  - module
  - current chapter
  - login status
  - hand-in status
  - current helper statistics (optional)
- possibility to quickly add new participants (or, at least, the link to hand out)
- possibility to look at hand-ins, accept, and reject them
- possibility to set levels for participants
- possibility to look at modules and chapters (optional)
