### ISSUE TITLE
Change the size of the webbrowser...

### ISSUE THREAD

**Issue by TheJackiMonster** [MarHai/iiigel#22]
It's always a problem. Just try to get all these 'div'-tags fix by putting them into more 'div'-tags or look for a better solution.

**Comment by MarHai** [comment]
please post links whre this takes place

**Comment by TheJackiMonster** [comment]
Here's a screenshot: http://intern.gag-if.de/wiki/uploads/170iiigel_new/thumb/e/e4/Bug3.png/1304px-Bug3.png

Some elements of bootstrap will be placed wrong if you change the size of the window.

**Comment by TheJackiMonster** [comment]
Should be fixed by commenting lines 21 to 24 in '/res/script/iiigel.js'..
